class FoodData {
  // this list contains all dessert
  static List<dynamic> dessertList = [["Cheesecake (100 g)","ชีสเค้ก (100 ก.)",321,"no","dessert","international"],
    ["Chocolate cake, without frosting (100 g)","เค้กช็อคโกแลต (ไม่มีไอซ์ซิ่ง 100 ก.)",371,"no","dessert","international"],
    ["Fruit cake (100 g)","เค้กผลไม้ (100 ก.)",324,"no","dessert","international"],
    ["Pan cake (100 g)","แพนเค้ก (100 ก.)",227,"no","dessert","international"],
    ["Pound cake (butter, 100 g)","เค้กปอนด์ (เนย 100 ก.)",388,"no","dessert","international"],
    ["Pound cake (fatfree, 100 g)","เค้กปอนด์ (ปราศจากไขมัน 100 ก.)",283,"no","dessert","international"],
    ["Shortcake (100 g)","ชอร์ทเค้ก (100 ก.)",346,"no","dessert","international"],
    ["Sponge cake (100 g)","สปันจ์เค้ก (100 ก.)",297,"no","dessert","international"],
    ["Foy thong (1 set)","ฝอยทอง (1 แพ)",220,"no","dessert","thailand"],
    ["Med kanoon (1 piece)","เม็ดขนุน (1 เม็ด)",40,"no","dessert","thailand"],
    ["Thong yod (1 piece)","ทองหยอด (1 ชิ้น)",30,"no","dessert","thailand"],
    ["Thong yib (1 piece)","ทองหยิบ (1 ชิ้น)",60,"no","dessert","thailand"],
    ["Mango with sticky rice (1 serving)","ข้าวเหนียวมะม่วง (1 จาน)",350,"no","dessert","thailand"],
    ["Sarim (1 serving)","ซ่าหริ่ม (1 ถ้วย)",275,"no","dessert","thailand"],
    ["Lodchong in coconut milk (1 serving)","ลอดช่องน้ำกะทิ (1 ถ้วย)",135,"no","dessert","thailand"],
    ["Pandan coconut milk jelly (1 piece)","วุ้นกะทิใบเตย (1 ชิ้น)",135,"no","dessert","thailand"],
    ["Kanom thuay (1 piece)","ขนมถ้วย (1 ชิ้น)",125,"no","dessert","thailand"],
    ["Thai candied banana with coconut milk (1 piece)","กล้วยไข่เชื่อม (1 ผล)",140,"no","dessert","thailand"],
    ["Sticky rice with custard (1 serving)","ข้าวเหนียวสังขยา (1  ห่อ)",370,"no","dessert","thailand"],
    ["Coconut milk ice cream (1 serving)","ไอศกรีมกะทิ (1 ถ้วย)",330,"no","dessert","thailand"],
    ["Kanom krok (1 piece)","ขนมครก (1 ชิ้น)",50,"no","dessert","thailand"],
    ["Kanom beung (1 piece)","ขนมเบื้อง (1 ชิ้น)",60,"no","dessert","thailand"],
    ["Banana in cococnut milk (1 serving)","กล้วยบวชชี (1 จาน)",250,"no","dessert","thailand"],
    ["Chocolate brownie (100 g)","ช็อกโกแลตบราวนี่ (100 ก.)",466,"no","dessert","international"],
    ["Waffle (100 g)","วาฟเฟิล (100 ก.)",291,"no","dessert","international"],
    ["Dark chocolate (100 g)","ดาร์กช็อกโกแลต (100 ก.)",546,"no","dessert","international"],
    ["White chocolate (100 g)","ไวท์ช็อกโกแลต (100 ก.)",539,"no","dessert","international"],
    ["Milk chocolate (100 g)","ช็อกโกแลตนม (100 ก.)",535,"no","dessert","international"],
    ["Ice cream (vanilla, 100 g)","ไอศกรีม (วานิลลา 100 ก.)",207,"no","dessert","international"],
    ["Ice cream (strawberry, 100 g)","ไอศกรีม (สตรอเบอร์รี่ 100 ก.)",192,"no","dessert","international"],
    ["Ice cream (chocolate, 100 g)","ไอศกรีม (ช็อคโกแลต 100 ก.)",216,"no","dessert","international"],
    ["Ice cream (chocolate, light, 100 g)","ไอศกรีม (ช็อคโกแลต, สูตรไขมันต่ำ 100 ก.)",187,"no","dessert","international"],
    ["Ice cream (vanilla, fatfree, 100 g)","ไอศกรีม (วานิลลาปราศจากไขมัน 100 ก.)",138,"no","dessert","international"],
    ["Ice cream (vanilla, light, 100 g)","ไอศกรีม (วานิลลา, สูตรไขมันต่ำ 100 ก.)",180,"no","dessert","international"],
    ["Muffins (blueberry, 100 g)","มัฟฟิน (บลูเบอร์รี่ 100 ก.)",377,"no","dessert","international"],
    ["Muffins (corn, 100 g)","มัฟฟิน (ข้าวโพด 100 ก.)",305,"no","dessert","international"],
    ["Muffins (oat bran, 100 g)","มัฟฟิน (รำข้าวโอ๊ต 100 ก.)",270,"no","dessert","international"],
    ["Muffins (plain, 100 g)","มัฟฟิน (ธรรมดา 100 ก.)",296,"no","dessert","international"],
    ["Muffins (wheat bran, raisins, 100 g)","มัฟฟิน (รำข้าวสาลี, ลูกเกด, 100 ก.)",295,"no","dessert","international"],
    ["Look choup (100 g)","ลูกชุบ (100 ก.)",600,"no","dessert","thailand"],
    ["Cookie (butter, 100 g)","คุกกี้ (เนย 100 กรัม)",467,"no","dessert","international"],
    ["Chocolate chip cookie (100 g)","คุกกี้ช็อกโกแลตชิป (100 กรัม)",488,"no","dessert","international"],
    ["Fortune cookie (100 g)","คุกกี้เสี่ยงทาย (100 กรัม)",378,"no","dessert","international"],
    ["Macaroons (with coconut, 100 g)","มาการอง (ใส่มะพร้าว 100 กรัม)",404,"no","dessert","international"],
    ["Oatmeal raisin cookie (100 g)","คุกกี้ข้าวโอ๊ตลูกเกด (100 กรัม)",435,"no","dessert","international"],
    ["Peanut butter cookie (100 g)","คุกกี้เนยถั่ว (100 กรัม)",475,"no","dessert","international"],
    ["Shortbread cookie (100 g)","คุกกี้บิสกิต (100 กรัม)",502,"no","dessert","international"],
    ["Doughnut (1 piece)","โรตีสายไหม (1 ชิ้น)",173,"no","dessert","international"],
    ["Greentea brownie (1 piece)","โรตีสายไหม (1 ชิ้น)",137,"no","dessert","international"],
    ["Glutinous rice pandan dumplings stuffed with candied and smoked coconut (1 piece)","ขนมต้ม  (1 ชิ้น)",52,"no","dessert","thailand"],
    ["Thai layer dessert (1 piece)","โรตีสายไหม (1 ชิ้น)",115,"no","dessert","thailand"],
    ["Thai pudding with coconut topping (1 serving)","ตะโก้  (1 ชิ้น)",78,"no","dessert","thailand"],
    ["Durian sticky rice (1 serving)","ข้าวเหนียวทุเรียน",340,"no","dessert","thailand"],
    ["Crispy coconut crepe (30 g)","ทองม้วนกรอบ   (30 ก.)",140,"no","dessert","thailand"],
    ["Soft coconut crepe (1 piece)","โรตีสายไหม (1 ชิ้น)",83,"no","dessert","thailand"],
    ["Thai cotton candy (1 piece)","โรตีสายไหม (1 ชิ้น)",145,"no","dessert","thailand"],
    ["Fried roti (1 serving)","โรตีทอด (แบบอาบัง)",590,"no","dessert","thailand"],
    ["Bingsu (M)","บิงซู (1 ชาม)",300,"no","dessert","international"],
    ["Bingsu (L)","บิงซู  (1 ชาม)",750,"no","dessert","international"],
    ["Crepe (1 piece)","เครป (1 ชิ้น.)",145,"no","dessert","international"],
    ["Pudding (100 g)","พุดดิ้ง (100 ก.)",120,"no","dessert","international"],
    ["Granola (100 g)","กราโนล่า (100 ก.)",471,"no","dessert","international"],
    ["Banoffee (1 serving)","บานอฟฟี่ (1 ชิ้น)",400,"no","dessert","international"],
    ["Pana cotta (100 g)","พานาคอตต้า (100 ก.)",223,"no","dessert","international"],
    ["Tiramisu (1 piece)","ทีรามิสุ (1 ชิ้น)",492,"no","dessert","international"],
    ["Apple Crumble Cake (1 piece)","แอปเปิ้ลครัมเบิลเค้ก (1 ชิ้น)",229,"no","dessert","international"],
    ["Moji (1 piece)","โมจิ (1 ชิ้น)",50,"no","dessert","international"],
    ["Daifuku (1 roll)","ไดฟูกุ (1 ชิ้น)",232,"no","dessert","international"],
    ["Thai Caramel (1 piece)","กาละแม (1 ชิ้น)",65,"no","dessert","international"],
    ["Croissant (S)","ครัวซองต์ (ชิ้นเล็ก)",171,"no","dessert","international"],
    ["Croissant (L)","ครัวซองต์ (ชิ้นใหญ่)",296,"no","dessert","international"],
    ["Water chestnuts in syrup and coconut milk (185 g)","ทับทิมกรอบ (185 g)",276,"no","dessert","thailand"],
    ["Coconut maracoon (1 piece)","บ้าบิ่น (1 ชิ้น)",130,"no","dessert","thailand"],
    ["Thai sweetmeat made of flour, egg and sugar (100 g)","ขนมผิง (100 ก.)",297,"no","dessert","thailand"],
    ["Nipa palm dessert (100 g)","ขนมจาก (100 ก.)",400,"no","dessert","thailand"],
    ["Sweet stuffed dough ( 1 piece)","ขนมใส่ไส้ (1 ชิ้น)",136,"no","dessert","thailand"],
    ["Chilled Santol in scented Syrup (1 serving)","กระท้อนลอยแก้ว (1 ถ้วย)",200,"no","dessert","thailand"],
    ["Snake fruit in syrup (1 serving)","สละลอยแก้ว (1 ถ้วย)",150,"no","dessert","thailand"],
    ["Rambutan stuffed pineapple (1 can)","เงาะยัดไส้สับปะรด (1 ถ้วย)",120,"no","dessert","thailand"],
    ["Khanom Tarn (1 piece)","ขนมตาล (1 ชิ้น)",32,"no","dessert","thailand"],
    ["Thai filled with coconut milk and banana (1 pair)","ข้าวต้มมัด (1 ชิ้น)",320,"no","dessert","thailand"],
    ["Thai sweet sticky rice with dried fish  (1 Serving)","ข้าวเหนียวหน้าปลาแห้ง (1. มัด)",180,"no","dessert","thailand"],
    ["Thai sweet sticky rice with dried shrimp (1 Serving)","ข้าวเหนียวหน้ากุ้ง (1 มัด)",180,"no","dessert","thailand"],
    ["Choux cream (1 piece)","ชูครีม (1 ชิ้น)",220,"no","dessert","international"],
    ["Eclair (100 g)","เอแคลร์ (100 ก.)",334,"no","dessert","international"],
    ["Nama chocolate (1 piece)","นามะ ช็อกโกแลต (1 ชิ้น)",30,"no","dessert","international"],
    ["Name green tea (1 piece)","นามะ ชาเขียว (1 ชิ้น)",31,"no","dessert","international"],
    ["Deep fried dough stick (1 piece)","ปาท่องโก๋ (1 ชิ้น)",69,"no","dessert","thailand"],
    ["Meringue (1 tart)","เมอแรงค์ (1 ชิ้น)",398,"no","dessert","international"],
    ["Scone (100 g)","สโคน (100 ก.)",353,"no","dessert","international"],
    ["Banana cake (1 serving)","เค้กกล้วยหอม (1 ชิ้น)",256,"no","dessert","international"],
    ["Turkish delight (100 g)","เตอร์กิช ดีไลท์ (100 ก.)",255,"no","dessert","international"],
    ["Sweet sago with camtaloupe (1 serving)","สาคูแคนตาลูป (1  ถ้วย)",160,"no","dessert","thailand"],
    ["Thai tea crepe (1 piece)","เครปเค้กชาไทย (1 ชิ้น)",156,"no","dessert","international"],
    ["Green tea crepe (1 piece)","เครปเค้กชาเขียว (1 ชิ้น)",156,"no","dessert","international"],
    ["Chocolate crepe  (1 piece)","เครปเค้กช็อกโกแลต (1 ชิ้น)",156,"no","dessert","international"],
    ["Horlick crepe  (1 piece)","เครปเค้กฮอลิค (1 ชิ้น)",156,"no","dessert","international"],
    ["Jam roll (1 piece)","แยมโรล (1 ชิ้น)",120,"no","dessert","international"],
    ["Chffon cake (100 g)","ชิฟฟ่อนเค้ก (100 ก.)",297,"no","dessert","international"],
    ["Thai custard bread (1 piece)","ขนมปังสังขยา (1 ชิ้น)",235,"no","dessert","thailand"],
    ["Stewed  pumpkin coconut milk (1 serving)","ฟักทองแกงบวช (1 ถ้วย)",165,"no","dessert","thailand"],
    ["Sweet sticky rice with longan (1 serving)","ข้าวเหนียวเปียกลำไย (1 มัด)",356,"no","dessert","thailand"],
    ["Sweet sticky rice with black peas (1 serving)","ข้าวเหนียวถั่วดำ (1 มัด)",279,"no","dessert","thailand"],
    ["Green beans in syrup (1 serving)","ถั่วเขียวต้มน้ำตาล (1 ถ้วย)",160,"no","dessert","thailand"],
    ["Thai mung bean pudding (1 serving)","เต้าส่วน (1 ถ้วย)",431,"no","dessert","thailand"],
    ["soybean curd (1 serving)","เต้าฮวยนมสด (1 ถ้วย)",218,"no","dessert","thailand"],
    ["Thai glutinous rice balls (1 serving)","บัวลอย (1 ถ้วย)",367,"no","dessert","thailand"],
    ["Season cake in coconut milk (1 serving)","ครองแครงน้ำกะทิ (1  ถ้วย)",250,"no","dessert","thailand"],
    ["Egg custard with mung bean flour (1 seving)","ขนมหม้อแกง (1 ถาด)",102,"no","dessert","thailand"],
    ["Corn flakes (1 cup)","คอร์นเฟล็ก (1 ชาม)",100,"no","dessert","international"],
    ["Taotheung (1 serving)","เต้าทึง (1 ถ้วย)",130,"no","dessert","thailand"],
    ["Thai rice flour full cup cake (1 piece)","ขนมถ้วยฟู (1 ชิ้น)",32,"no","dessert","thailand"],
    ["Bamboo sticky rice (1 serving)","ข้าวหลาม (1 คู่)",230,"no","dessert","thailand"],
    ["Honey toast (1 piece)","ฮันนี่โทสต์ (1 ชิ้น)",492,"no","dessert","international"],
    ["Chocolate lava (100 g)","ช็อกโกแลตลาวา (100 ก.)",448,"no","dessert","international"],
    ["cinnamon roll (100 g)","ซินนามอนโรล (100 ก.)",361,"no","dessert","international"],
    ["Soft mung bean crepe (1 servig)","ถั่วแปป (1 จาน)",117,"no","dessert","thailand"],
    ["Soft waffle (1 piece)","ขนมโตเกียว (1 ชิ้น)",147,"no","dessert","international"],
    ["Leum Kleun (1 serving)","ขนมลืมกลืน (1 ถ้วย)",326,"no","dessert","thailand"],
    ["Steamed rice flour (1 serving)","ขนมขี้หนู (1 ถ้วย)",165,"no","dessert","thailand"],
    ["Sticky rice in banan leaf with syrup (1 serving)","ข้าวต้มน้ําวุ้น (1มัด)",240,"no","dessert","thailand"],
    ["New year's cake (1 piece)","ขนมเข่ง (100 ก.)",120,"no","dessert","thailand"],
    ["Thai sweet cereal bar (1 serving)","กระยาสารท (100 ก.)",210,"no","dessert","thailand"],
    ["Butter bread (100 g)","ขนมปังเนยสด (100 ก.)",269,"no","dessert","international"],
    ["Chinese cake (100 g)","ขนมเปี๊ยะ (100 ก.)",207,"no","dessert","thailand"],
    ["Dried mango paste (100 g)","มะม่วงกวน (100 ก.)",340,"no","dessert","thailand"],
    ["Dred durian paste (100 g)","ทุเรียนกวน (100 ก.)",340,"no","dessert","thailand"]];

  static List<dynamic> drinksList = [["A&W Root Beer 355 ml","รูทเบียร์ A&W 355 ml",170,"no","drink","Soft drink"],
    ["Coca-Cola 325 ml","โค้ก 325 ml",140,"no","drink","Soft drink"],
    ["Coca-Cola Zero 325 ml","โค้กซีโร่ 325 ml",0,"no","drink","Soft drink"],
    ["Fanta Orange 325 ml","แฟนต้าส้ม 325 ml",180,"no","drink","Soft drink"],
    ["Fanta Red 325 ml","แฟนต้าแดง 325 ml",200,"no","drink","Soft drink"],
    ["Fanta Green 325 ml","แฟนต้าเขียว 325 ml",200,"no","drink","Soft drink"],
    ["Sprite 325 ml","สไปรท์ 325 ml",130,"no","drink","Soft drink"],
    ["Sprite no sugar 325 ml","สไปรท์ ไม่มีน้ำตาล 325 ml",0,"no","drink","Soft drink"],
    ["Sponsor 325 ml","สปอนเซอร์ 325 ml",140,"no","drink","Soft drink"],
    ["Schweppes Lime Soda 330 ml","ชเวปส์ มะนาวโซดา 330 ml",170,"no","drink","Soft drink"],
    ["Iced Coffee with Milk 16 oz (Grande)","กาแฟเย็นใส่นม 16 oz (Grande)",110,"no","drink","Coffee"],
    ["Iced Black Coffee 16 oz (Grande)","กาแฟเย็น 16 oz (Grande)",80,"no","drink","Coffee"],
    ["Iced Caffè Latte 16 oz (Grande)","ลาเต้เย็น 16 oz (Grande)",130,"no","drink","Coffee"],
    ["Iced Caramel Macchiato 16 oz (Grande)","คาราเมลมัคคิอาโตเย็น 16 oz (Grande)",250,"no","drink","Coffee"],
    ["Iced Caffè Americano 16 oz (Grande)","อเมริกาโนเย็น 16 oz (Grande)",15,"no","drink","Coffee"],
    ["Iced Caffè Mocha 16 oz (Grande)","มอคค่าเย็น 16 oz (Grande)",350,"no","drink","Coffee"],
    ["Hot Espresso 1.5 oz (Doppio)","เอสเพรสโซ่ร้อน 1.5 oz (Doppio)",10,"no","drink","Coffee"],
    ["Hot Caffè Americano 16 oz (Grande)","อเมริกาโนร้อน 16 oz (Grande)",15,"no","drink","Coffee"],
    ["Hot Cappuccino 16 oz (Grande)","คาปูชิโน่ร้อน 16 oz (Grande)",120,"no","drink","Coffee"],
    ["Hot Caffè Latte 16 oz (Grande)","ลาเต้ร้อน 16 oz (Grande)",190,"no","drink","Coffee"],
    ["Hot Caramel Macchiato 16 oz (Grande)","คาราเมลมัคคิอาโตร้อน 16 oz (Grande)",250,"no","drink","Coffee"],
    ["Hot Caffè Mocha 16 oz (Grande)","มอคค่าร้อน 16 oz (Grande)",360,"no","drink","Coffee"],
    ["Coffee Frappuccino 16 oz (Grande)","กาแฟปั่น 16 oz (Grande)",230,"no","drink","Coffee"],
    ["Espresso Frappuccino 16 oz (Grande)","เอสเพรสโซ่ปั่น 16 oz (Grande)",210,"no","drink","Coffee"],
    ["Mocha Frappuccino 16 oz (Grande)","มอคค่าปั่น 16 oz (Grande)",370,"no","drink","Coffee"],
    ["Iced Black Tea 16 oz (Grande)","ชาดำเย็น (Black Tea) 16 oz (Grande)",45,"no","drink","Tea"],
    ["Iced Matcha Green Tea Latte 16 oz (Grande)","ลาเต้ชาเขียวเย็น 16 oz (Grande)",200,"no","drink","Tea"],
    ["Iced Green Tea 16 oz (Grande)","ชาเขียวเย็น 16 oz (Grande)",45,"no","drink","Tea"],
    ["Hot Earl Grey Tea 16 oz (Grande)","ชาเอิร์ลเกรย์ร้อน 16 oz (Grande)",0,"no","drink","Tea"],
    ["Hot Matcha Green Tea Latte 16 oz (Grande)","ลาเต้ชาเขียวร้อน 16 oz (Grande)",240,"no","drink","Tea"],
    ["Matcha Green Tea Crème Frappuccino 16 oz (Grande)","ชาเขียวปั่นใส่วิปครีม 16 oz (Grande)",410,"no","drink","Tea"],
    ["Iced Lemon Tea 200 ml","ชามะนาว 200 ml",100,"no","drink","Tea"],
    ["Thai Iced Tea 200 ml","ชาไทยเย็น/ชานมเย็น 200 ml",319,"no","drink","Tea"],
    ["Thai Black Tea 200 ml","ชาดำเย็น 200 ml",110,"no","drink","Tea"],
    ["Bubble Milk Tea 200 ml","ชานมไข่มุก 200 ml",360,"no","drink","Tea"],
    ["Double Chocolaty Chip Crème Frappuccino 16 oz (Grande)","ช็อคโกแลตปั่น 16 oz (Grande)",400,"no","drink","Cold drink"],
    ["Hot Chocolate 16 oz (Grande)","ช็อคโกแลตร้อน 16 oz (Grande)",400,"no","drink","Cold drink"],
    ["Iced Chocolate 200 ml","ช็อคโกแลตเย็น 200 ml",334,"no","drink","Cold drink"],
    ["Pink Milk 200 ml","นมชมพูเย็น 200 ml",425,"no","drink","Cold drink"],
    ["Soy Milk 200 ml","นมถั่วเหลือง 200 ml",140,"no","drink","Cold drink"],
    ["Fermented Milk 80 ml","นมเปรี้ยว 80 ml",71,"no","drink","Cold drink"],
    ["Milk 225 ml","นมจืด 225 ml",150,"no","drink","Cold drink"],
    ["Orange Juice 240 ml","น้ำส้มคั้น 240 ml",110,"no","drink","Juice"],
    ["Tomato Juice 240 ml","น้ำมะเขือเทศ 240 ml",42,"no","drink","Juice"],
    ["Coconut Juice 240 ml","น้ำมะพร้าว 240 ml",120,"no","drink","Juice"],
    ["Strawberry juice 240 ml","น้ำสตอเบอร์รี่ 240 ml",90,"no","drink","Juice"],
    ["Lemon Juice 240 ml","น้ำมะนาว 240 ml",53,"no","drink","Juice"],
    ["Beer Regular 355 ml","เบียร์ 355 ml",153,"no","drink","Alcohol"],
    ["Whiskey (80 proof) 45 ml","วิสกี้ 40 ดีกรี 45 ml",97,"no","drink","Alcohol"],
    ["Red Wine 5 oz","ไวน์แดง 5 oz",125,"no","drink","Alcohol"]];

  static List<dynamic> ingredientsList = [["Almonds (100 g)","อัลมอนด์ (100 ก.)",884,"no","ingredient","grains"],
    ["Apple (riped, 100 g)","แอปเปิ้ล (สุก, 100 ก.)",52,"no","ingredient","fruit"],
    ["Bacon (baked, 100 g)","เบคอน (อบ, 100 ก.)",548,"no","ingredient","meat"],
    ["Banana (riped, 100 g)","กล้วย (สุก, 100 ก.)",89,"no","ingredient","fruit"],
    ["Beef (raw, 100 g)","เนื้อวัว (ดิบ, 100 ก.)",250,"no","ingredient","meat"],
    ["Beef chuck (raw, 100 g)","เนื้อหัวใหล่วัว (ดิบ, 100 ก.)",277,"no","ingredient","meat"],
    ["Beef flank (raw, 100 g)","เนื้อพื้นท้องวัว (ดิบ, 100 ก.)",192,"no","ingredient","meat"],
    ["Beef plate (raw, 100 g)","เนื้อหน้าท้องวัว (ดิบ, 100 ก.)",293,"no","ingredient","meat"],
    ["Beef round (raw, 100 g)","เนื้อสะโพกวัว (ดิบ, 100 ก.)",182,"no","ingredient","meat"],
    ["Beef short lion (broiled, 100 g)","เนื้อสะโพกวัว (ดิบ, 100 ก.)",282,"no","ingredient","meat"],
    ["Beef short ribs  (braised, 100 g)","ซี่โครงวัว (ดิบ, 100 ก.)",471,"no","ingredient","meat"],
    ["Beef sirlion (broiled, 100 g)","เนื้อสันนอกวัว (ดิบ, 100 ก.)",244,"no","ingredient","meat"],
    ["Beef tenderloin (roast, 100 g)","เนื้อสันในวัว (ดิบ, 100 ก.)",324,"no","ingredient","meat"],
    ["Beef top sirlion (raw, 100 g)","เนื้อสันนอกวัว (ดิบ, 100 ก.)",244,"no","ingredient","meat"],
    ["Brisket (raw, 100 g)","เนื้อเสือร้องไห้ (ดิบ, 100 ก.)",155,"no","ingredient","meat"],
    ["Cabbage (raw, 100 g)","กะหล่ำปลี (ดิบ, 100 ก.)",25,"no","ingredient","veggies"],
    ["Cashew nut (100 g)","เม็ดมะม่วงหิมพานต์ (100 ก.)",553,"no","ingredient","grains"],
    ["Cheddar cheese (100 g)","เชดดาร์ชีส (100 ก.)",371,"no","ingredient","dairy"],
    ["Cherry tomato (raw, 100 g) ","มะเขือเทศเชอร์รี่ (ดิบ, 100 ก.)",25,"no","ingredient","veggies"],
    ["Chicken breast (raw, 100 g)","อกไก่ (ดิบ, 100 ก.)",165,"no","ingredient","meat"],
    ["Chicken drumstick (raw, 100 g)","น่องไก่ (ดิบ, 100 ก.)",173,"no","ingredient","meat"],
    ["Chicken egg (raw, 1 egg) ","ไข่ไก่ (ดิบ, 1 ฟอง)",70,"no","ingredient","meat"],
    ["Chicken thighs (raw, 100 g)","สะโพกไก่ (ดิบ, 100 ก.)",177,"no","ingredient","meat"],
    ["Chicken wing (raw, 100 g)","ปีกไก่ (ดิบ, 100 ก.)",203,"no","ingredient","meat"],
    ["Durian (riped, 100 g)","ทุเรียน (สุก, 100 ก.)",357,"no","ingredient","fruit"],
    ["Granola (100 g)","กราโนล่า (สุก, 100 ก.)",471,"no","ingredient","grains"],
    ["Grape (riped, 100 g)","องุ่น (สุก, 100 ก.)",67,"no","ingredient","fruit"],
    ["Green chilli (100 g)","พริกเขียว (100 ก.)",40,"no","ingredient","veggies"],
    ["Ham (whole, roasted, 100 g)","แฮม (ย่าง, 100 ก.)",243,"no","ingredient","meat"],
    ["Hazelnuts (100 g)","เฮเซลนัท (100 ก.)",628,"no","ingredient","grains"],
    ["Lamb (raw, 100 g)","เนื้อแกะ (ดิบ, 100 ก.)",294,"no","ingredient","meat"],
    ["Macadamia nuts (100 g)","ถั่วมะคาเดเมีย (100 ก.)",718,"no","ingredient","grains"],
    ["Mango (riped, 100 g)","มะม่วง (สุก, 100 ก.)",60,"no","ingredient","fruit"],
    ["Milk (whole, 3.25% fat, 100 g)","นม (ไขมัน 3.25%, 100 ก.)",61,"no","ingredient","dairy"],
    ["Mutton (raw, 100 g)","เนื้อแกะ (ดิบ, 100 ก.)",294,"no","ingredient","meat"],
    ["Onion (raw, 100 g)","หัวหอม (ดิบ, 100 ก.)",40,"no","ingredient","veggies"],
    ["Oyster sauce (100 g)","ซอสหอยนางรม (100 ก.)",51,"no","ingredient","flavoring"],
    ["Passion fruit (riped, 100 g)","เสาวรส (สุก, 100 ก.)",97,"no","ingredient","fruit"],
    ["Pecans nut (100 g)","ถั่วพีแคน (100 ก.)",690,"no","ingredient","grains"],
    ["Pineapple (riped, 100 g)","สับปะรด (สุก, 100 ก.)",50,"no","ingredient","fruit"],
    ["Pork (raw, 100 g)","เนื้อหมู (ดิบ, 100 ก.)",145,"no","ingredient","meat"],
    ["Pork belly (raw, 100 g)","หมูสามชั้น (ดิบ, 100 ก.)",518,"no","ingredient","meat"],
    ["Pork lion (broiled, 100 g)","เนื้อซี่โครงหมู (ย่าง, 100 ก.)",242,"no","ingredient","meat"],
    ["Pork spareribs (broiled, 100 g)","ซี่โครงหมู (ย่าง, 100 ก.)",318,"no","ingredient","meat"],
    ["Potato (raw, 100 g)","มันฝรั่ง (ดิบ, 100 ก.)",77,"no","ingredient","veggies"],
    ["Pumpkin (raw, 100 g)","ฟักทอง (ดิบ, 100 ก.)",26,"no","ingredient","veggies"],
    ["Quail egg (raw, 1 egg) ","ไข่นกกระทา (ดิบ, 1 ฟอง.)",15,"no","ingredient","meat"],
    ["Rice (raw, 100 g)","ข้าว (ดิบ, 100 ก.)",130,"no","ingredient","grains"],
    ["Soy sauce (100 g)","ซีอิ๊ว (100 ก.)",53,"no","ingredient","flavoring"],
    ["Strawberry (riped, 100 g)","สตรอเบอร์รี่ (สุก, 100 ก.)",33,"no","ingredient","fruit"],
    ["Sugar (100 g)","น้ำตาล (100 ก.)",387,"no","ingredient","flavoring"],
    ["Tomato (raw, 100 g) ","มะเขือเทศ (ดิบ, 100 ก.)",18,"no","ingredient","veggies"],
    ["Turkey meat (raw, 100 g)","เนื้อไก่งวง (ดิบ, 100 ก.)",189,"no","ingredient","meat"],
    ["Yardlong bean (raw, 100 g) ","ถั่วฝักยาว (ดิบ, 100 ก.)",47,"no","ingredient","veggies"],
    ["Yogurt (Greek, nonfat, 100 g)","โยเกิร์ต (กรีก, ไม่มีไขมัน, 100 ก.)",59,"no","ingredient","dairy"],
    ["Bread (Bagel, 100 g)","ขนมปัง (เบเกิล 100 ก.)",250,"no","ingredient","carb"],
    ["Banana bread (100 g)","ขนมปังกล้วย (100 ก.)",326,"no","ingredient","carb"],
    ["Bread (pumpernickel, 100 g)","ขนมปัง (ข้าวไร, 100 ก.)",250,"no","ingredient","carb"],
    ["Bread (rye, 100 g)","ขนมปัง (ข้าวไรย์ 100 ก.)",259,"no","ingredient","carb"],
    ["Bread (toasted, 100 g)","ขนมปังปิ้ง (100 ก.)",313,"no","ingredient","carb"],
    ["Bread (white, 100 g)","ขนมปัง (ขาว 100 ก.)",265,"no","ingredient","carb"],
    ["Croissant (butter, 100 g)","ครัวซองต์ (เนย 100 ก.)",406,"no","ingredient","carb"],
    ["English muffins (100 g)","มัฟฟินอังกฤษ (100 ก.)",235,"no","ingredient","carb"],
    ["Focaccia (100 g)","ขนมปังโฟคาเซีย  (100 ก.)",250,"no","ingredient","carb"],
    ["Garlic bread (100 g)","ขนมปังกระเทียม (100 ก.)",350,"no","ingredient","carb"],
    ["Pita bread (white, unenriched, 100 g)","ขนมปัง Pita (ขาว 100 ก.)",275,"no","ingredient","carb"],
    ["Raisin bread (100 g)","ขนมปังลูกเกด (100 ก.)",274,"no","ingredient","carb"],
    ["Small bread (100 g)","ขนมปังขนาดเล็ก (100 ก.)",310,"no","ingredient","carb"],
    ["Sausage (pork and beef, Polish, smoked, 100 g)","ไส้กรอกโปแลนด์ (หมูและเนื้อ, รมควัน, 100 กรัม)",301,"no","ingredient","meat"],
    ["Hot dog (pork, 100 g)","ฮอทดอก (เนื้อหมู 100 กรัม)",269,"no","ingredient","meat"],
    ["Sausage (beef, cooked, 100 g)","ไส้กรอก (เนื้อวัว, สุก, 100 กรัม)",331,"no","ingredient","meat"],
    ["Lamb (whole, 1/4'' fat, 100 g)","เนื้อแกะ (ไขมัน 1/4 นิ้ว, 100 กรัม)",230,"no","ingredient","meat"],
    ["Lamb (loin, 1/4'' fat, 100 g)","เนื้อซี่โครงแกะ (ไขมัน 1/4 นิ้ว, 100 กรัม)",310,"no","ingredient","meat"],
    ["Lamb (shoulder, whole, 0.25 inch fat, 100 g)","เนื้อแกะ (ไหล่, ทั้งหมด, ไขมัน 1/4 นิ้ว, 100 กรัม)",264,"no","ingredient","meat"],
    ["Lamb (0.25 inches fat, 100 g)","เนื้อแกะ (ไขมัน 1/4 นิ้ว, 100 กรัม)",267,"no","ingredient","meat"],
    ["Lamb (heart, 100g)","หัวใจแกะ ( 100 กรัม)",122,"no","ingredient","meat"],
    ["Lamb (kidney, 100 g)","ไตแกะ (100 กรัม)",97,"no","ingredient","meat"],
    ["Lamb (liver, 100 g)","ตับแกะ (100 กรัม)",139,"no","ingredient","meat"],
    ["White mushroom (100 g)","เห็ดขาว (100 กรัม)",22,"no","ingredient","veggies"],
    ["Artichokes (100 g)","อาร์ติโช้ค (100 กรัม)",47,"no","ingredient","veggies"],
    ["Asparagus (100 g)","หน่อไม้ฝรั่ง (100 กรัม)",20,"no","ingredient","veggies"],
    ["Brussels sprouts (100 g)","บรัสเซลส์ถั่วงอก (100 กรัม)",43,"no","ingredient","veggies"],
    ["Cauliflower (100 g)","กะหล่ำดอก (100 กรัม)",25,"no","ingredient","veggies"],
    ["Ginger (root, 100 g)","ขิง (100 กรัม)",80,"no","ingredient","veggies"],
    ["Green bean (100 g)","ถั่วเขียว (100 กรัม)",31,"no","ingredient","veggies"],
    ["Leeks (100 g)","ต้นกระเทียม (100 ก.)",61,"no","ingredient","veggies"],
    ["Lettuce (green leaf, 100 g)","ผักกาดหอม (ใบเขียว 100 กรัม)",15,"no","ingredient","veggies"],
    ["Raddish (100 g)","หัวใช้เท้า (100 ก.)",16,"no","ingredient","veggies"],
    ["Shallots (100 g)","หอมแดง (100 กรัม)",72,"no","ingredient","veggies"],
    ["Fava beans (raw, 100 g)","ถั่วฟาวา (ดิบ 100 กรัม)",88,"no","ingredient","veggies"],
    ["Rhubarb  (100 g)","รูบาร์บ (100 กรัม)",21,"no","ingredient","veggies"],
    ["Scallions (100 g)","ต้นหอม (100 กรัม)",32,"no","ingredient","veggies"],
    ["Avocados (100 g)","อะโวคาโด (100 กรัม)",160,"no","ingredient","fruit"],
    ["Cherry (red, 100 g)","เชอร์รี่ (แดง 100 กรัม)",50,"no","ingredient","fruit"],
    ["Chilli (red, 100 g)","พริก (แดง 100 กรัม)",40,"no","ingredient","fruit"],
    ["Eggplant (100 g)","มะเขือยาว (100 กรัม)",25,"no","ingredient","fruit"],
    ["Kiwi (100 g)","กีวี่ (100 กรัม)",61,"no","ingredient","fruit"],
    ["Lemon (100 g)","เลม่อน (100 กรัม)",66,"no","ingredient","fruit"],
    ["Lychee (100 g)","ลิ้นจี่ (100 กรัม)",66,"no","ingredient","fruit"],
    ["Peach  (100 g)","พีช (100 กรัม)",39,"no","ingredient","fruit"],
    ["Watermelon (100 g)","แตงโม (100 กรัม)",30,"no","ingredient","fruit"],
    ["Zucchini (100 g)","ซูกินี่ (100 กรัม)",17,"no","ingredient","fruit"],
    ["Jalapeno pepper (100 g)","พริกจาลาเปโน่ (100 กรัม)",28,"no","ingredient","fruit"]];

  static List<dynamic> mealList = [["Rice Noodle with soup","ก๋วยจั๊บ",240,"no","meal","china","no"],
    ["Vietnamese Rice Noodle","ก๋วยจั๊บญวณ",235,"no","meal","other","no"],
    ["Laksa","ก๋วยเตี๋ยวแขก",380,"no","meal","other","no"],
    ["Fried rice noodle with chicken","ก๋วยเตี๋ยวคั่วไก่",435,"no","meal","thai","Northern"],
    ["Tom yum koong rice noodle","ก๋วยเตี๋ยวต้มยำกุ้ง",320,"no","meal","thai","other"],
    ["Beef Noodles","ก๋วยเตี๋ยวเนื้อเรียง",370,"no","meal","thai","other"],
    ["Minced beef with rice noodles","ก๋วยเตี๋ยวเนื้อสับ",370,"no","meal","thai","other"],
    ["Stir fried chicken with noodles","ก๋วยเตี๋ยวผัดกะเพราไก่",440,"no","meal","thai","other"],
    ["Pad thai with shrimp and egg","ก๋วยเตี๋ยวผัดไทยกุ้งสดไส่ไข่",545,"no","meal","thai","other"],
    ["Chinese noodle with snapper in gravy sauce","ก๋วยเตี๋ยวราดหน้าปลากระพง",435,"no","meal","thai","other"],
    ["Thai boat noodles","ก๋วยเตี๋ยวเรือน้ำตก",180,"no","meal","thai","other"],
    ["Thai boat noodles (dry)","ก๋วยเตี๋ยวเรือน้ำตกแห้ง",225,"no","meal","thai","other"],
    ["Fish noodle","ก๋วยเตี๋ยวเส้นปลา",375,"no","meal","thai","other"],
    ["Fish noodle (dry)","ก๋วยเตี๋ยวเส้นปลาแห้ง",420,"no","meal","thai","other"],
    ["Tom yum rice noodle with pork","ก๋วยเตี๋ยวเส้นเล็กต้มยำหมู",335,"no","meal","thai","other"],
    ["Tom yum rice noodle with pork (dry)","ก๋วยเตี๋ยวเส้นเล็กหมูแห้ง",330,"no","meal","thai","other"],
    ["Chinese rice noodle with egg,pork, in gravy sauce","ก๋วยเตี๋ยวเส้นใหญ่ผัดซีอิ้วใส่ไข่",520,"no","meal","thai","other"],
    ["Chinese rice noodle with pork in gravy sauce","ก๋วยเตี๋ยวเส้นใหญ่ราดหน้าหมู",405,"no","meal","thai","other"],
    ["Wrapped rice noodle","ก๋วยเตี๋ยวหลอด",225,"no","meal","china","no"],
    ["Meat ball noodle soup","เกาเหลาลูกชิ้นน้ำใส",225,"no","meal","china","no"],
    ["Crispy wonton topped with shrimp","เกี๊ยวกรอบราดหน้ากุ้ง",635,"no","meal","china","no"],
    ["Shrimp wonton soup","เกี๊ยวน้ำกุ้ง",275,"no","meal","china","no"],
    ["Fish wonton soup","เกี๊ยวปลาน้ำ",165,"no","meal","china","no"],
    ["Crispy noodles in thick gravy","โกยซีหมี่",550,"no","meal","china","no"],
    ["Fermented rice noodle in coconut milk","ขนมจีนซาวน้ำ",320,"no","meal","thai","other"],
    ["Fermented rice noodle with chilli paste","ขนมจีนน้ำพริก",450,"no","meal","thai","other"],
    ["Fermented rice noodle in coconut gravy","ขนมจีนน้ำยา",375,"no","meal","thai","other"],
    ["Fried radish","ขนมผักกาดผัด",560,"no","meal","thai","other"],
    ["Fried radish with eggs","ขนมผักกาดผัดใส่ไข่",630,"no","meal","thai","other"],
    ["Fermented rice noodle","ขนมจีน",180,"no","meal","thai","other"],
    ["Deep fried egg noodles in gravy sauce","ราดหน้าหมี่กรอบ",515,"no","meal","thai","other"],
    ["Deep fried egg noodles with all meat in gravy sauce","ราดหน้าหมี่กรอบรวมมิตร",690,"no","meal","thai","other"],
    ["Fried instant noodle with holy basil and pork","บะหมี่กึ่งสำเร็จรูปผัดกะเพราใส่หมู",540,"no","meal","thai","other"],
    ["Fried herby instant noodle","บะหมี่กึ่งสำเร็จรูปผัดขี้เมา",530,"no","meal","thai","other"],
    ["Egg noodle with poached chicken","บะหมี่ไก่ตุ๋นน้ำ",375,"no","meal","thai","other"],
    ["Egg noodle with pork in tomyum soup","บะหมี่น้ำต้มยำหมู",330,"no","meal","thai","other"],
    ["Egg noodle with roasted duck","บะหมี่เป็ดน้ำ",370,"no","meal","thai","other"],
    ["Egg noodle with Chinese roasted pork (dry)","บะหมี่หมูแดงแห้ง",345,"no","meal","thai","other"],
    ["Fried herby macaroni with chicken","มักกะโรนีขี้เมาไก่",520,"no","meal","thai","other"],
    ["Fermented rice noodle salad","ยำขนมจีน",220,"no","meal","thai","other"],
    ["Yen ta four","เย็นตาโฟน้ำ",290,"no","meal","thai","other"],
    ["Sukiyaki chicken","สุกี้ยากี้ไก่น้ำ",345,"no","meal","thai","other"],
    ["Stir fried rice noodle with crab","เส้นจันทร์ผัดปู",280,"no","meal","thai","other"],
    ["Rice noodle with meat balls (clear soup)","เส้นหมี่ลูกชิ้นน้ำใส",575,"no","meal","thai","other"],
    ["Rice noodle with meat balls (dry)","เส้นหมี่ลูกชิ้นหมูแห้ง",225,"no","meal","thai","other"],
    ["Noodles in coconut milk","หมี่กะทิ",690,"no","meal","thai","other"],
    ["Pad si eew with pork and egg","ผัดซีอิ้วหมูใส่ไข่",679,"no","meal","thai","other"],
    ["Yen ta four with rice noodles","ก๋วยเตี๋ยวเส้นใหญ่เย็นตาโฟน้ำ",352,"no","meal","thai","other"],
    ["Rice noodle with pork (dry)","ก๋วยเตี๋ยวเส้นเล็กแห้งหมู",530,"no","meal","thai","other"],
    ["Rice noodle with beef meatballs","เส้นหมี่ลูกชิ้นเนื้อวัว",226,"no","meal","thai","other"],
    ["Rice noodle with fresh beef","เส้นหมี่เนื้อสดน้ำ",256,"no","meal","thai","other"],
    ["Rice noodle with poached beef and fresh beef","เส้นหมี่เนื้อสด เนื้อเปื่อยน้ำ",298,"no","meal","thai","other"],
    ["Shrimp in Fish Sauce","กุ้งแช่น้ำปลา",14,"no","meal","thai","other"],
    ["Stir Fried Shrimp with Garlic","กุ้งทอดกระเทียมพริกไทย",86,"no","meal","thai","other"],
    ["Stir-fried Shrimp with Green Pepper","กุ้งผัดพริกหยวก",235,"no","meal","thai","other"],
    ["Chicken Green Curry","แกงเขียวหวานไก่",240,"no","meal","thai","other"],
    ["Catfish Green Curry","แกงเขียวหวานปลาดุก",235,"no","meal","thai","other"],
    ["Clown knifefish Green Curry","แกงเขียวหวานลูกชิ้นปลากราย",240,"no","meal","thai","other"],
    ["Pork Green Curry","แกงเขียวหวานหมู",235,"no","meal","thai","other"],
    ["Clear Soup with Tofu and Minced Pork","แกงจืดไข่เจียว",120,"no","meal","thai","other"],
    ["Clear Soup with Ivy Gourd and Minced Pork","แกงจืดตำลึงหมูสับ",90,"no","meal","thai","other"],
    ["Clear Soup with Egg Tofu","แกงจืดเต้าหู้ไม่ใส่หมูสับ",80,"no","meal","thai","other"],
    ["Clear Soup with Stuffed Egg Tofu","แกงจืดเต้าหู้ยัดไส้",110,"no","meal","thai","other"],
    ["Clear Soup with Pork-Stuffed Squash","แกงจืดฟักยัดไส้",90,"no","meal","thai","other"],
    ["Clear Soup with Pork-Stuffed Gourd","แกงจืดมะระยัดไส้",90,"no","meal","thai","other"],
    ["Clear Soup with Vermicelli and Pork-Stuffed Gourd","แกงจืดมะระยัดไส้หมูวุ้นเส้น",66,"no","meal","thai","other"],
    ["Clear Soup with Vermicelli","แกงจืดวุ้นเส้น",85,"no","meal","thai","other"],
    ["Chicken Jungle Curry","แกงป่าไก่ ",110,"no","meal","thai","other"],
    ["Red Curry with Chicken and Eggplant","แกงเผ็ดไก่ใส่มะเขือ ",235,"no","meal","thai","other"],
    ["Red Curry with Chicken and Banboo Shoot","แกงเผ็ดไก่ใส่หน่อไม้ ",245,"no","meal","thai","other"],
    ["Roasted Duck Red Curry","แกงเผ็ดเป็ดย่าง ",240,"no","meal","thai","other"],
    ["Fish Ball Red Curry","แกงเผ็ดลูกชิ้นปลา",240,"no","meal","thai","other"],
    ["Coconut Shoot and Pork Curry ","แกงเผ็ดหมูยอดมะพร้าว ",245,"no","meal","thai","other"],
    ["Thai Spicy Mixed Vegetable Soup","แกงเลียง",115,"no","meal","thai","other"],
    ["Sour Curry","แกงส้ม",28,"no","meal","thai","other"],
    ["Sour Curry with Vegetabel Omelet and Prawns","แกงส้มชะอมไข่ทอดใส่กุ้ง",270,"no","meal","thai","other"],
    ["Sour Curry with Agasta and Prawns","แกงส้มดอกแคกุ้ง ",105,"no","meal","thai","other"],
    ["Sour Curry with Whole Fish","แกงส้มปลาแป๊ะซะ ",160,"no","meal","thai","other"],
    ["Stir-fried Ginger Chicken","ไก่ผัดขิง",210,"no","meal","thai","other"],
    ["Rice with Stif-fried beef and Basil","ข้าวกะเพราเนื้อ",622,"no","meal","thai","other"],
    ["Stir-fried Shrimp with Garlic","ข้าวกุ้งทอดกระเทียม",495,"no","meal","thai","other"],
    ["Chicken Red Curry Rice","ข้าวแกงเผ็ดไก่",485,"no","meal","thai","other"],
    ["Stewed Pork Leg on Rice","ข้าวขาหมู",690,"no","meal","thai","other"],
    ["Omelet Rice","ข้าวไข่เจียว",445,"no","meal","thai","other"],
    ["Crispy rice cake and pork and shrimp dipping","ข้าวตังหน้าตั้ง",90,"no","meal","thai","other"],
    ["Crispy Pork Belly with Thai Basil","ข้าวผัดกะเพราหมูกรอบ",650,"no","meal","thai","other"],
    ["Rice with Stif-fried Shrimp and Basil","ข้าวผัดกะเพรากุ้ง",540,"no","meal","thai","other"],
    ["Rice with Stif-fried Chicken and Basil","ข้าวผัดกะเพราไก่",554,"no","meal","thai","other"],
    ["Rice with Stif-fried Chicken and Basil and Fried Egg","ข้าวผัดกะเพราไก่ไข่ดาว",630,"no","meal","thai","other"],
    ["Rice with Stif-fried Pork and Basil","ข้าวผัดกะเพราหมู",580,"no","meal","thai","other"],
    ["Fried Rice with Shrimp and Egg","ข้าวผัดกุ้งใส่ไข่",595,"no","meal","thai","other"],
    ["Fried Rice with Shrimp and Chinese Saussage","ข้าวผัดกุนเชียง",590,"no","meal","thai","other"],
    ["Green Curry Fried Rice with Chicken","ข้าวผัดแกงเขียวหวานไก่",630,"no","meal","thai","other"],
    ["Fried Rice with Cryspy Pork and Kale","ข้าวผัดคะน้าหมูกรอบ",670,"no","meal","thai","other"],
    ["Tom Yum Seafood Fried Rice ","ข้าวผัดต้มยำทะเลแห้ง",400,"no","meal","thai","other"],
    ["Fermented rice noodle in herby coconut milk","ขนมจีนน้ำเงี้ยว",305,"no","meal","thai","Northern"],
    ["Khao Soi Chicken","ข้าวซอยไก่",395,"no","meal","thai","Northern"],
    ["Khao Soi Pork","ข้าวซอยหมู",395,"no","meal","thai","Northern"],
    ["Fried Shrimp","กุ้งฝอยชุบแป้งทอด",308,"no","meal","thai","Northern"],
    ["Chicken Red Curry with Bamboo Shoot","แกงเผ็ดหน่อไม้ไก่ ",245,"no","meal","thai","Northern"],
    ["Chilled Rice","ข้าวแช่",350,"no","meal","thai","Northern"],
    ["Shrimp Paste Rice","ข้าวคลุกกะปิ",410,"no","meal","thai","Southern"],
    ["Hot yellow Seer fish curry with pickled bamboo shoots","แกงเหลืองหน่อไม้ดองกับปลา",80,"no","meal","thai","Southern"],
    ["Massaman Curry with Chicken","แกงมัสมั่นไก่ ",325,"no","meal","thai","Southern"],
    ["Red Curry with Smoked Dry Fish and Coconut Milk","แกงขี้เหล็ก",195,"no","meal","thai","Southern"],
    ["Red Curry with Smoked Dry Fish, Grilled Pork, and Coconut Milk","แกงขี้เหล็กหมูย่าง",245,"no","meal","thai","Southern"],
    ["Fish Organs Sour Soup","แกงไตปลา ",50,"no","meal","thai","Southern"],
    ["Fried Rice with Chilli Paste and Shrimp","ข้าวผัดน้ำพริกกุ้งสด",460,"no","meal","thai","Southern"],
    ["Roasted Chicken","ไก่ย่าง",165,"no","meal","thai","isarn"],
    ["Crispy rice cake and pork and flossy pork","ข้าวตังหมูหยอง",80,"no","meal","thai","isarn"],
    ["Pork Dumpling","ขนมจีบหมู",32,"no","meal","china","no"],
    ["Egg noodle with wonton and roasted duck","บะหมี่เกี๊ยวเป็ดย่าง",415,"no","meal","china","no"],
    ["Egg noodle with Chinese roasted pork and wonton","บะหมี่เกี๊ยวหมูแดงน้ำ",305,"no","meal","china","no"],
    ["Stir fried Chinese egg noddle","ผัดหมี่ซั่ว",405,"no","meal","china","no"],
    ["Rice noodle","ก๋วยจั๊บน้ำใส",259,"no","meal","china","no"],
    ["Rice noodle (condensed)","ก๋วยจั๊บน้ำข้น",270,"no","meal","china","no"],
    ["Fish Maw Soup","กระเพาะปลา",150,"no","meal","china","no"],
    ["Casseroled Shrimp with Glass Noodle ","กุ้งอบวุ้นเส้น",300,"no","meal","china","no"],
    ["Steamed Shrimp with Garlic","กุ้งนึ่งกระเทียมโทน",124,"no","meal","china","no"],
    ["Fried Chives Dumpling","กุยช่ายทอด",114,"no","meal","china","no"],
    ["Yakisoba","ยากิโซบะ",400,"no","meal","japan","no"],
    ["Chicken Curry Rice","ข้าวแกงกะหรี่ไก่",389,"no","meal","japan","no"],
    ["Gyoza","เกี๊ยวซ่า",63,"no","meal","japan","no"],
    ["Chicken Curry","แกงกะหรี่ไก่",450,"no","meal","japan","no"],
    ["Pork Curry","แกงกะหรี่หมู",325,"no","meal","japan","no"],
    ["Fried macaroni with shrimp","มักกะโรนีผัดกุ้ง",420,"no","meal","western","no"],
    ["Pho noodle","เส้นเฝอ",240,"no","meal","other","no"],
    ["KFC Chicken Thigh","ไก่ KFC สะโพก",355,"no","meal","other","no"],
    ["KFC Hot Wings","ไก่ KFC ฮอตวิง",78,"no","meal","other","no"],
    ["Fried Chicken","ไก่ทอด",345,"no","meal","other","no"],
    ["Roasted Chicken on Rice","ข้าวไก่อบ",490,"no","meal","other","no"],
    ["Brown Rice Porridge","ข้าวต้ม (ข้าวกล้อง)",120,"no","meal","other","no"],
    ["White Rice Porridge","ข้าวต้ม (ข้าวขาว)",120,"no","meal","other","no"],
    ["Congee with Pork and Egg","ข้าวต้มทรงเครื่อง",230,"no","meal","other","no"],
    ["Fish Porridge","ข้าวต้มปลา",325,"no","meal","other","no"],
    ["Nam Prik Long Rua Fried Rice","ข้าวผัดน้ำพริกลงเรือ",605,"no","meal","thai","other"],
    ["Salted Fish Fried Rice","ข้าวผัดปลาเค็ม",405,"no","meal","thai","other"],
    ["Crab Meat Fried Rice","ข้าวผัดปูใส่ไข่",610,"no","meal","thai","other"],
    ["Pineapple Fried Rice","ข้าวผัดสับปะรด",335,"no","meal","thai","other"],
    ["Sausage Fried Rice","ข้าวผัดไส้กรอก",520,"no","meal","thai","other"],
    ["American Fried Rice","ข้าวผัดอเมริกัน",790,"no","meal","thai","other"],
    ["Rice with Savoury Curry and Beef","ข้าวพะแนงเนื้อ",457,"no","meal","thai","other"],
    ["Chicken Rice","ข้าวมันไก่",596,"no","meal","thai","other"],
    ["Fried Chicken Rice","ข้าวมันไก่ทอด",695,"no","meal","thai","other"],
    ["Rice with Chicken in Chicken Gravy","ข้าวราดหน้าไก่",400,"no","meal","thai","other"],
    ["Rice with Chicken Stew","ข้าวสตูไก่",465,"no","meal","thai","other"],
    ["Duck Rice","ข้าวหน้าเป็ด",495,"no","meal","thai","other"],
    ["Rice with Roasted Pork","ข้าวหมูแดง",541,"no","meal","thai","other"],
    ["Rice with Fried Pork","ข้าวหมูทอด",416,"no","meal","thai","other"],
    ["Rice with Garlic-fried Pork","ข้าวหมูทอดกระเทียม",525,"no","meal","thai","other"],
    ["Baked Rice with Pork","ข้าวหมูอบ",389,"no","meal","thai","other"],
    ["Salted Egg","ไข่เค็ม",75,"no","meal","thai","other"],
    ["Thai Omelet","ไข่เจียว",215,"no","meal","thai","other"],
    ["Fried Egg","ไข่ดาว",215,"no","meal","thai","other"],
    ["Stewed Egg","ไข่พะโล้",180,"no","meal","thai","other"],
    ["Thai Stuffed Omelet","ไข่ยัดไส้",310,"no","meal","thai","other"],
    ["Soft-boiled eggs","ไข่ลวก",75,"no","meal","thai","other"],
    ["Kai Luk Koei (Son-in-law Egg) ","ไข่ลูกเขย",205,"no","meal","thai","other"],
    ["Crispy Pork Belly with Kale","คะน้าหมูกรอบ",420,"no","meal","thai","other"],
    ["Thai Chicken Coconut Soup","ต้มข่าไก่",210,"no","meal","thai","other"],
    ["Blood Tofu Soup with Pork","ต้มจืดเลือดหมู",120,"no","meal","thai","other"],
    ["Tom Yum Kung","ต้มยำกุ้ง",65,"no","meal","thai","other"],
    ["Tom Ka Kai","ต้มยำไก่",60,"no","meal","thai","other"],
    ["Chicken Tom Yum with Mushrooms","ต้มยำไก่ใส่เห็ด",80,"no","meal","thai","other"],
    ["Canned Fish Tom Yum","ต้มยำปลากระป๋อง",55,"no","meal","thai","other"],
    ["Sea Bass Tom Yum","ต้มยำปลากะพง",80,"no","meal","thai","other"],
    ["Fresh Mushroom Tom Yum","ต้มยำเห็ดสด",30,"no","meal","thai","other"],
    ["Fried Fish Cake","ทอดมันปลากราย",37,"no","meal","thai","other"],
    ["Sweet and Sour Fried Fish","ปลาทอดสามรส",470,"no","meal","thai","other"],
    ["Fried Mackerel","ปลาทูทอด",280,"no","meal","thai","other"],
    ["Grilled Fish","ปลาเผา",156,"no","meal","thai","other"],
    ["Fried Salted King Mackerel","ปลาอินทรีเค็มทอด",115,"no","meal","thai","other"],
    ["Fried Chicken Wings","ปีกไก่ทอด",107,"no","meal","thai","other"],
    ["Fried Cabbage with Pork","ผัดกะหล่ำปลีหมู",230,"no","meal","thai","other"],
    ["Kale with Salted Fish","ผัดคะน้าปลาเค็ม",200,"no","meal","thai","other"],
    ["Stir Fried Bean Sprouts and Tofu","ผัดถั่วงอกเต้าหู้",155,"no","meal","thai","other"],
    ["Pad Thai with Prawns","ผัดไทยกุ้งสด",486,"no","meal","thai","other"],
    ["Pad Thai with Prawns and Egg","ผัดไทยกุ้งสดใส่ไข่",545,"no","meal","thai","other"],
    ["Stir Fried Sweet and Sour Chicken","ผัดเปรี้ยวหวานไก่",215,"no","meal","thai","other"],
    ["Stir Fried Morning Glory","ผัดผักบุ้งไฟแดง",210,"no","meal","thai","other"],
    ["Stir Fried Crispy Catfish","ผัดเผ็ดปลาดุก",200,"no","meal","thai","other"],
    ["Stir Fried Eggplant with Porka and Basil","ผัดมะเขือยาวหมูสับ",210,"no","meal","thai","other"],
    ["Stir Fried Pumpkin with Egg","ผัดฟักทองใส่ไข่",255,"no","meal","thai","other"],
    ["Spicy Canned Sardine Salad","ยำปลากระป๋อง",55,"no","meal","thai","other"],
    ["Crispy Catfish Salad","ยำปลาดุกฟู",275,"no","meal","thai","other"],
    ["Spicy Crispy Morning Glory Salad","ยำผักบุ้งทอดกรอบ",310,"no","meal","thai","other"],
    ["Glass Noodle Salad","ยำวุ้นเส้น",120,"no","meal","thai","other"],
    ["Crispy Pork Belly","หมูกรอบ",560,"no","meal","thai","other"],
    ["Grilled Pork","หมูปิ้ง",125,"no","meal","thai","other"],
    ["Stir Fried Pork with Ginger","หมูผัดขิง",275,"no","meal","thai","other"],
    ["Salted Crab in Dipping Sauce","หลนปูเค็ม",205,"no","meal","thai","other"],
    ["Baked Mussels in Clay Pot","หอยแมลงภู่อบหม้อดิน",17,"no","meal","thai","other"],
    ["Fried Rice with Minced Pork with Salted Olives and Egg","ข้าวผัดหนำเลี้ยบหมูใส่ไข่",370,"no","meal","thai","Northern"],
    ["Miang Kham","เมี่ยงคำ",30,"no","meal","thai","Northern"],
    ["Spicy Pickled Cababge Salad","ยำผักกาดดอง",30,"no","meal","thai","Northern"],
    ["Chicken Biryani","ข้าวหมกไก่",534,"no","meal","thai","Southern"],
    ["Stir Fried Pork with Ginger and Cowpea","ผัดพริกขิงหมูถั่วฝักยาว",265,"no","meal","thai","Southern"],
    ["Roasted Chicken Thigh","น่องไก่ย่าง",97,"no","meal","thai","isarn"],
    ["Num Tok Beef","เนื้อน้ำตก",165,"no","meal","thai","isarn"],
    ["Sticky Rice with Pork","ข้าวเหนียวหมูทอด",440,"no","meal","thai","isarn"],
    ["Sticky Rice with Mhoo Sawan","ข้าวเหนียวหมูสวรรค์",480,"no","meal","thai","isarn"],
    ["Chilli Paste Fried Rice with Shrimp","ข้าวผัดน้ำพริกเผาหมู",665,"no","meal","thai","isarn"],
    ["Grilled Pork Neck","คอหมูย่าง",200,"no","meal","thai","isarn"],
    ["Grilled Pork Salad","ยำหมูย่าง",165,"no","meal","thai","isarn"],
    ["Chicken Larb","ลาบไก่",125,"no","meal","thai","isarn"],
    ["Beef Larb","ลาบเนื้อ",119,"no","meal","thai","isarn"],
    ["Pork Larb","ลาบหมู",119,"no","meal","thai","isarn"],
    ["Som Tum (no nuts)","ส้มตำ ไม่ใส่ถั่ว",80,"no","meal","thai","isarn"],
    ["Som Tum Thai (no nuts)","ส้มตำไทย ไม่ใส่ถั่ว",55,"no","meal","thai","isarn"],
    ["Crab Som Tum (no nuts)","ส้มตำปู ไม่ใส่ถั่ว",35,"no","meal","thai","isarn"],
    ["Crab Som Tum Thai (no nuts)","ส้มตำปูไทย ไม่ใส่ถั่ว",118,"no","meal","thai","isarn"],
    ["Isarn Sausage","ไส้กรอกอีสาน",90,"no","meal","thai","isarn"],
    ["Mhoo Num Tok","หมูน้ำตก",165,"no","meal","thai","isarn"],
    ["Grilled Chicken Chest ","อกไก่ย่าง",110,"no","meal","thai","isarn"],
    ["Porridge with Egg","โจ๊กใส่ไข่",250,"no","meal","china","no"],
    ["Pork Porridge","โจ๊กหมู",160,"no","meal","china","no"],
    ["Pork Porridge with Soft-boiled Egg","โจ๊กหมูตับ ใส่ไข่ลวก",230,"no","meal","china","no"],
    ["Fried Buns","ซาลาเปาทอด",157,"no","meal","china","no"],
    ["Pork Buns","ซาลาเปาไส้หมู",202,"no","meal","china","no"],
    ["Pork Intestine with Picked Cabbage Soup","ต้มตือฮวน",160,"no","meal","china","no"],
    ["Chinese Stewed Duck","เป็ดพะโล้",110,"no","meal","china","no"],
    ["Fried Saba","ปลาซาบะย่าง",220,"no","meal","japan","no"],
    ["Fried Salmon","ปลาแซลมอนย่าง",260,"no","meal","japan","no"],
    ["Fried Chicken Steak with Mashed Potato","สเต๊กไก่ทอด + มันบด",615,"no","meal","western","no"],
    ["Fried Fish Steak","สเต๊กปลาย่าง",260,"no","meal","western","no"],
    ["Pork Stead with Salad","สเต๊กหมู + ผักสลัด",505,"no","meal","western","no"],
    ["Shrimp Salad","สลัดกุ้ง",92,"no","meal","western","no"],
    ["Shicken Salad","สลัดไก่",97,"no","meal","western","no"],
    ["Roasted Chicken Chest","อกไก่อบ",169,"no","meal","western","no"],
    ["Fried Chicken Thigh","น่องไก่ทอด",345,"no","meal","other","no"],
    ["Fried Pork Ball","ลูกชิ้นทอด",35,"no","meal","other","no"],
    ["Fried Beef Ball","ลูกชิ้นเนื้อวัว",8,"no","meal","other","no"],
    ["Fried Fish Ball","ลูกชิ้นปลา",4,"no","meal","other","no"]];

  static List<dynamic> snackList = [["Potato chips (100 g)","มันฝรั่งทอด (100 ก)",536,"no","snack"],
    ["Potato chips (barbecue flavor, 100 g)","มันฝรั่งทอด (รสบาร์บีคิว 100 ก)",490,"no","snack"],
    ["Potato chips (cheese flavor, 100 g)","มันฝรั่งทอด (รสชีส 100 ก)",551,"no","snack"],
    ["Potato chips (salted, 100 g)","มันฝรั่งทอด (เค็ม 100 ก)",542,"no","snack"],
    ["Potato chips (sour cream and onion flavor, 100 g)","มันฝรั่งทอด (รสซาวครีมและหัวหอม 100 ก)",547,"no","snack"],
    ["Candy (100 g)","ลูกอม (100 กรัม)",535,"no","snack"],
    ["Tao Kae Noi Seaweed (28 g)","สาหร่ายทอดกรอบ เถ้าแก่น้อย (28 ก)",200,"no","snack"],
    ["Tao Kae Noi Seaweed (45 g)","สาหร่ายทอดกรอบ เถ้าแก่น้อย  (45 ก)",340,"no","snack"],
    ["Masita Seaweed (12 g)","สาหร่ายทอดกรอบ มาชิตะ (12 ก)",80,"no","snack"],
    ["Masita Seaweed (30 g)","สาหร่ายทอดกรอบ มาชิตะ (30 ก)",200,"no","snack"],
    ["Lays Nori Seaweed (50 g)","เลย์รสสาหร่าย (50 ก)",320,"no","snack"],
    ["Lays Nori Seaweed (75 g)","เลย์รสสาหร่าย (75 ก)",390,"no","snack"],
    ["Lays Tom Yun Kung (50 g)","เลย์รสต้มยำกุง (50 ก)",320,"no","snack"],
    ["Lays Tom Yun Kung (75 g)","เลย์รสต้มยำกุง (75 ก)",390,"no","snack"],
    ["Lays Original (50 g)","เลย์รสดั้งเดิม (50 ก)",320,"no","snack"],
    ["Lays Original (75 g)","เลย์รสดั้งเดิม (75 ก)",390,"no","snack"],
    ["Lays Squid (50 g)","เลย์รสปลาหมึกย่าง (50 ก)",320,"no","snack"],
    ["Lays Sour Cream and Onion (158 g)","เลย์รสซาวครีมและหัวหอม (158 ก)",800,"no","snack"],
    ["Lays Sour Cream and Onion (75 g)","เลย์รสซาวครีมและหัวหอม (75 ก)",400,"no","snack"],
    ["Lays Salted Eggs (146 g)","เลย์รสไข่เค็ม (146 ก)",800,"no","snack"],
    ["Lays Salted Eggs (70 g)","เลย์รสไข่เค็ม (70 ก)",400,"no","snack"],
    ["Lays Miangkum (75 g)","เลย์รสเหมี่ยงคำ (75 ก)",390,"no","snack"],
    ["Lays Spicy Lemon (75 g)","เลน์รสพริกและมะนาว (75 ก)",390,"no","snack"],
    ["Ka-kai (Chicken Leg) (100 g)","ขาไก่ (100 ก)",215,"no","snack"],
    ["Pote (32 g)","โปเต้ (32 ก)",300,"no","snack"],
    ["Pote (65 g)","โปเต้ (65 ก)",600,"no","snack"],
    ["Conne (56 g)","คอนเน่ (56 ก)",300,"no","snack"],
    ["Paprika (32 g)","ปาปริก้า (32 ก)",170,"no","snack"],
    ["Paprika (65 g)","ปาปริก้า (65 ก)",340,"no","snack"],
    ["Party (30 g)","ปาร์ตี้ (30 ก)",140,"no","snack"],
    ["Party (60 g)","ปาร์ตี้ (60 ก)",280,"no","snack"],
    ["Karamujo Potato Chips (48 g)","มันฝรั่งทอดกรอบ คารามูโจ้ (48 ก.)",260,"no","snack"],
    ["Karamujo Potato Chips (100 g)","มันฝรั่งทอดกรอบ คารามูโจ้ (100 ก.)",520,"no","snack"],
    ["Bento Dried Squid (20 g)","ปลาหมึกย่าง เบนโตะ (20 ก.)",60,"no","snack"],
    ["Bento Dried Squid (30 g)","ปลาหมึกย่าง เบนโตะ (30 ก.)",110,"no","snack"],
    ["Dozo (1 small package)","โดโซะ (1 ห่อเล็ก)",28,"no","snack"],
    ["Koh-kae Salted Peanuts (42 g)","โก๋แก่ ถั่วลิสงอบเกลือ (42 ก.)",250,"no","snack"],
    ["Koh-kae Salted Cashew Nuts (28 g)","โก๋แก่ พลัส เมล็ดมะม่วงหิมพานต์อบเกลือ (30 ก)",180,"no","snack"],
    ["Koh-kae Almonds (28 g)","โก๋แก่ พลัส ถั่วอัลมอนด์อบเกลือ (28 ก)",170,"no","snack"],
    ["Koh-kae Original (40 g)","โก๋แก่ ออริจินัล ถั่วลิสงอบกรอบ รสกะทิ (40 ก)",250,"no","snack"],
    ["Koh-kae Wasabi Peanuts (30 g)","โก๋แก่ ถั่วลิสงอบกรอบเคลือบวาซาบิ (30 ก.)",150,"no","snack"],
    ["Koh-kae Salted Peanuts (30 g)","โก๋แก่ ถั่วลิสงฝักอบกรอบชนิดเค็ม (30 ก.)",190,"no","snack"],
    ["Campus (30 g)","แคมปัส (30 ก)",130,"no","snack"],
    ["Roller Coaster (54 g)","โรลเลอร์ โคสเตอร์ (54 ก)",340,"no","snack"],
    ["Roller Coaster (94 g)","โรลเลอร์ โคสเตอร์ (94 ก)",510,"no","snack"],
    ["Snack Jack (34 g)","สแนคแจ็ค (34 ก) ",180,"no","snack"],
    ["Snack Jack (70 g)","สแนคแจ็ค (70 ก) ",360,"no","snack"],
    ["Taro (30 g)","ทาโร่ (30 ก)",100,"no","snack"],
    ["Taro (78 g)","ทาโร่ (78 ก)",240,"no","snack"],
    ["Dried banana slices coated with sugar (30 g)","กล้วยฉาบ (30 ก)",150,"no","snack"],
    ["Fried banana (1 piece)","กล้วยทอด (1 ชิ้น)",50,"no","snack"],
    ["Sun-dried banana (1 piece)","กล้วยตาก (1 ชิ้น)",60,"no","snack"],
    ["Banana chips (100 g)","กล้วยเบรคแตก (100 ก)",518,"no","snack"],
    ["Durna chips (100 g)","ทุเรียนทอด (7-8 ชิ้น)",50,"no","snack"],
    ["Popcorn (100 g)","ป๊อปคอร์น (100 ก)",375,"no","snack"],
    ["Testo (150 g)","เทสโต (150 ก)",800,"no","snack"],
    ["Testo (75 g)","เทสโต (75 ก)",390,"no","snack"],
    ["Manora Shrimp crisp rice","ข้าวเกรียบกุ้ง มโนราห์ (68 ก)",330,"no","snack"],
    ["Ruay Pen Shrimp crisp rice","ข้าวเกรียบกุ้ง รวยเพื่อน (68 ก)",330,"no","snack"],
    ["Calby Shrimp crisp rice (68 g)","ข้าวเกรียบกุ้ง คาลบี้ (68 ก)",330,"no","snack"],
    ["Hanami Shrimp crisp rice (60 g)","ข้าวเกรียบกุ้ง ฮานามิ (60 ก)",300,"no","snack"],
    ["Sunbite (28 )","ขนมธัญพืชอบกรอบ ซันไบทส์ (28 ก)",140,"no","snack"],
    ["Sunbite (56 g)","ขนมธัญพืชอบกรอบ ซันไบทส์ (56 ก)",280,"no","snack"],
    ["Karada Squid (68 g)","คาราด้า รสปลาหมึก (68 ก)",300,"no","snack"],
    ["Karada Squid (42 g)","คาราด้า รสปลาหมึก (42 ก)",180,"no","snack"],
    ["Cheetos (35 g)","ชีโตส (35 ก)",200,"no","snack"],
    ["Cheetos (70 g)","ชีโตส (70 ก)",390,"no","snack"],
    ["Twisty Twice (59 g)","ทวิสตี้ ทไวซ์ (59 ก)",200,"no","snack"],
    ["Sunflower seeds (100 g)","เมล็ดทานตะวัน(100 ก)",584,"no","snack"],
    ["Pumpkin seeds (100 g)","เมล็ดฟักทอง (100 ก)",446,"no","snack"],
    ["Collon (54 g)","โคล่อน (54 ก)",260,"no","snack"],
    ["Pocky (49 g)","ป๊อกกี้ (49 ก)",240,"no","snack"]];

}
